### ISSUE TITLE
Top search responses for county watch list

### ISSUE THREAD

**Issue by ashleydraper** [cagov/covid19#1057]
"Watch list" is a top trending search, but is not yielding optimal results on the front end. Considering a hidden QA that points users to the county monitoring list on the [county page](https://docs.google.com/document/d/1bz5oU2idZ3heF4GLQY7d1jhFVSiylFUbdnDKcAoeFQ0/edit#).
@abquirarte

**Comment by abquirarte** [comment]
@ashleydraper @thepegisin 

To add to this task, including @kkoryaka who may have design ideas around this. 

There is confusion between our accordion that lists affected counties (more than 3 days) vs. what is on the map. Users expect to see the full list in the accordion, but only 33 of the 35 will be affected. Yet the Governor references the full list in his pressers. 

How might we better design and capture this information so that users don't get lost between the accordion of the 33 (counties over 3 days) and the map. Could it be as simple as adding 2 accordions and a new header for "counties on monitoring list?"

`Counties over 3 consecutive days'
`Counties on less than 3 consecutive days' `

GO heard from a reporter: 
>The list I was reviewing is:
>https://covid19.ca.gov/roadmap-counties/#top
>Seems likely to cause confusion if the list I was reading (which is on the main website) isn’t maintained.

**Comment by thepegisin** [comment]
If we're going to maintain this list, we have to update it daily.  My suggestions:

- [ ]  Alphabetize it. Currently "San Francisco" and "Ventura" are out of place.
- [ ]  Since the GO is treating this as one list, add the under 3 days counties, with a notation:
        - Butte (on list less than 3 days)
        - Kern (on list less than 3 days)

**Comment by ashleydraper** [comment]
Good stuff Peggy! I had a thought to have the 33 alphabetized together and a bold note separating Butte and Kern beneath. Sounds like you want them all in one list with a note aside the 2 counties.

**Comment by abquirarte** [comment]
I think one accordion.

**Comment by thepegisin** [comment]
To get back to the original issue, could you add "watch list" in the text of the County page? That might make it appear higher in the search on "watch list." I'll suggest a good place in the doc.

**Comment by thepegisin** [comment]
Published these changes per @abquirarte's request 7pm 7/22. 

- [ ]  Check that a search on "watch list" brings up this page high in search results.

**Comment by thepegisin** [comment]
CML now appears as top search result when you search on "watch list." Closing this issue.
