### ISSUE TITLE
Are pools open? Need a more direct answer

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#1156]
Found 4 questions in per-page feedback since 7/17 about whether pools are allowed to be open. "Pools" is the #27 all-time search term, with 1,076 searches. The search brings up the gyms guidance PDF first, which says pools can be open, but that's not true if it's an indoor pool in a county on the CML. Think we need a better answer.

- [x] Write "Are pools open?" Q/A for **Stay home** page under **Outdoor recreation**. Specify that pools can be open statewide if they're outdoor, and in counties not on the CML if they're indoor. Link to gyms guidance and guidance for campgrounds, RV parks, and outdoor recreation.
- [x] Get SME approval
- [x] Publish

**Comment by LizNobriga** [comment]
See `Additional Considerations for Swimming Pools and Aquatic Venues` on page 15 of the [guidance PDF for Campgrounds, RV parks, and outdoor recreation](https://files.covid19.ca.gov/pdf/guidance-campgrounds.pdf), which addresses what's allowed for indoor and outdoor swimming pools, as well as water parks.  

- Campground, RV park, and **outdoor recreation operators with swimming pools and splash pads** should take additional steps to ensure those facilities are properly cleaned and disinfected for visitor use, according to CDC guidelines.

- Campgrounds, RV parks, and **outdoor recreation operators that have swimming pools which include water slides, water rides, or other water attractions must keep those areas closed until such operations can resume. Swimming pools themselves can remain open.**

- Please note that **saunas, steam rooms, and hot tubs** should remain closed until such operations can resume.

- For indoor pools, face coverings must be work (worn, typo in pdf) when out of the water or shower areas, unless exempt from the CDPH guidance. Cloth face coverings can be difficult to breathe through when they are wet. Face coverings should be put away when not in use so they are not accidentally touched or picked up by others. For outdoor pools, face coverings must be worn when out of the water whenever six-foot physical distancing cannot be maintained, unless exempt under the CDPH guidance.

- Maintain proper disinfectant levels (1-10 parts per million free chlorine or 3-8 ppm bromine) and pH (7.2-8).

- Consult with the company or engineer that designed the aquatic venue to decide which List N disinfectants approved by the EPA are best for the aquatic venue. Ensure the safe and correct use and storage of disinfectants, including storing products securely away from children.

- Set up a system so that furniture and equipment (e.g., lounge chairs) that need to be cleaned and disinfected are kept separate from furniture that has already been cleaned and disinfected. Label containers for used equipment that has not yet been cleaned and disinfected and containers for cleaned and disinfected equipment.

- Encourage visitors to bring and use their own towels. If towels are provided, launder them and clothing according to the manufacturer’s instructions. Use the warmest appropriate water temperature and dry items completely. Handle towels with disposable gloves and minimal disturbance, i.e., do not shake them.

- Discourage people from sharing items, particularly those that are difficult to clean and disinfect or those that are meant to come in contact with the face (e.g., goggles, nose clips, and snorkels).

- Ensure that the facility has adequate equipment for patrons, such as kickboards, pool noodles, and other flotation devices, to minimize sharing wherever possible. Limit the use of the equipment to one patron at a time and clean and disinfect the items after each use.

- **For indoor aquatic venues, introduce and circulate outdoor air as much as possible by opening windows and doors, using fans, or other methods. However, do not open windows and doors if doing so poses a safety risk to workers, visitors, or swimmers.**

- Change the deck layout and other areas surrounding the pool to ensure that the standing and seating areas can support physical distancing requirements. This could include removing lounge chairs or taping off areas to discourage use.

- Provide physical cues or guides (e.g., lane lines in the water or chairs and tables on the deck) and visual cues (e.g., tape on the decks, floors, or sidewalks) and signs to ensure that workers, visitors, and swimmers stay at least six feet apart from one another, both in and out of the water.

- Where feasible, install impermeable physical barriers such as Plexiglas where workers and patrons must interact and physical distancing is difficult.

- Consider implementing reservations for pool use or implementing other mechanisms to support physical distancing. This could include reserving full lanes for individual lap swimming and half-lanes for individual household use.

- Ensure that lifeguards who are actively lifeguarding are not also expected to monitor handwashing, use of cloth face coverings, or physical distancing. Assign this monitoring responsibility to another worker.

- **Aquatic venues should avoid activities that promote group gatherings and should be aware of local policies on gathering requirements to determine if aquatic fitness classes, swim lessons, swim team practices, swim meets, or pool parties can be held.**

- CDC’s Model Aquatic Health Code has more recommendations to prevent illness and injuries **at public pools in parks.**

**Comment by thepegisin** [comment]
Thanks, @LizNobriga! That was helpful.

@abquirarte, "Are swimming pools open?" Q/A is now in [Staging doc](https://docs.google.com/document/d/1xY5kma1vIJ6F32E_B9K_rAP51Rg_oNZ7k6WIka_4mIA/edit#) awaiting your approval.
