### ISSUE TITLE
Chatbot functionality

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#142]
Explore chatbot options for covid19.ca.gov.

Connected with the team 4//8/2020. There _may_ be an opportunity to help us streamline content curation through chatbot set-up. 

Timeline- Not now, we need to prioritize translations first, but taking notes. 

#### Considerations:
- Would be better than search
- More engaging which is what people are seeking during "stay home order"
- helps with analytics as it learns 
- centralizes content in a more organized way
- we could start by feeding it the FAQs we have in place now 
- This could also inform the scripts for the call center 

#### Other Notes:
- Could be a distraction
- Why not start with improving our IA and search first? 
- Hard to maintain?

**Comment by abquirarte** [comment]
Needs more learning lol 
![image](https://user-images.githubusercontent.com/9556188/77951239-933e4980-727e-11ea-8a3f-2ceb046b8941.png)

**Comment by carterm** [comment]
Chadbot code deployed on this dev site here ---
https://netwebsitetest.azurewebsites.net/

**Comment by aaronhans** [comment]
We expect the default integration to have negative impact on performance. They are doing things pretty responsibly but still loading several javascript files for the floating widget interaction. The impact when testing locally is -10 points on mobile lighthouse performance score and an additional second in the time to interactive measurement. 

These effects are not good especially because the majority of visitors will not be interacting with the chatbot. They can be avoided if we integrate differently. @artuoma mentioned he didn't like the floating integration anyway. We can do several things, here are some ideas:
- add button to our page to launch the chatbot which delays loading their assets until clicked or takes user to new chatbot dedicated page
- use Art's idea to integrate into search results page

**Comment by carterm** [comment]
We had/have the same issue with translate, we solved it by only activating the translate code when they click the translate link.  We could have the same functionality for chatbot.

**Comment by ChadABratton** [comment]
I added account access for the team, let me know if you did not get an email. Also loaded the initial set of questions for education, financial help, public places, etc....

**Comment by aaronhans** [comment]
I think the main priority for the chatbot is to have it reviewed by content experts to see where it works and fails. There is a lot of opportunity for customization with the questions it is able to answer. It is more powerful than other ML powered bots we saw demonstrated but still needs to be fed each content update either manually or via the API. It automatically created answers from our FAQ pages but it failed to fully parse all the content in our FAQ and was unable to parse the CDPH FAQ page at all so will need additional content manually inserted

**Comment by carterm** [comment]
A hidden page for the chat bot is deployed here...
https://covid19.ca.gov/google-chat-bot-test/

**Comment by aaronhans** [comment]
We have explored chatbot options. We currently use some conversational AI functionality in our quick answers on our search page, but nothing as interactive as a chatbot. I believe we are not going to prioritize development of a chatbot further and should close this
