### ISSUE TITLE
Dimmer Switch -- Post-Launch Bugs open as of 9-3-20

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1563]
this is freaking cool but might defer until after launch:
- [ ] save state in url, populate html5 history for back button updates, load based on params

Design

- [ ] **Move “Understanding your county’s status” header and paragraph copy above the matrix [P0]**
- [ ] **Intro paragraph (“California has a new…”) should be larger (same size as H4 text)  [P0]**
- [ ] Search result title (e.g. “Movie theaters in Fresno are Open”) should be smaller (the size of P text)  [P1]
- [ ] In the Activity dropdown, add horizontal rule to separate the “view all” links from the list of matching activities  [P1]
- [ ] Format dropdowns to match Figma (for hover color use F2F5FC as the bg)  [P1]
- [ ] For search results, match spacing to Figma so that the list is more compact  [P1]
- [ ] For the matrix in mobile, reduce spacing between rows of data in each tier so that each colored tier is less tall (i.e. reduce space between the tier / daily new cases / positive tests by 50% to reduce overall height)  [P1]
- [ ] Make map container full width OR centered in column [P1]
- [ ] Remove “county” and “activity” labels that appear above search input fields (unless these are there for accessibility reason?) [P1]
- [ ] Add period after "closed" in this sentence in the county header - "Many non-essential indoor business operations are closed Understand the data."
- [ ] Update the color of text labels on the tiers (widespread, moderate, etc.) to match Figma for accessibility reasons [P1]

Functionality

- [ ] Do not show search results until a user has pressed the "Get latest updated" button  [P1]
- [ ] Zip code search
- [ ] “Understand the data” anchor link should jump to the matrix (not the FAQ)

Content

- [ ] Can industry guidance links go directly to the guidance for that industry instead of all activities having the same link? 

Uncategorized

**Comment by aaronhans** [comment]
Some of the ones I'd like to discuss with design and user experience, possibly user test are:
- save state in url, populate html5 history for back button updates, load based on params
- Do not show search results until a user has pressed the "Get latest updated" button [P1]
- Remove “county” and “activity” labels that appear above search input fields (unless these are there for accessibility reason?) [P1] Consistently visually present labels are always preferred for accessibility. If we have a serious design need not to preserve visible labels we need to take extreme measures and run extra levels of usability tests to make sure the form still works for all users

Some of these which are already spinning off into additional tickets because they are complex:
- Can industry guidance links go directly to the guidance for that industry instead of all activities having the same link? https://github.com/cagov/covid19/issues/1561
- Zip code search: https://github.com/cagov/covid19/issues/1565 https://github.com/cagov/covid19/issues/1558 plus additional tickets to finish frontend once both of those are done

**Comment by kenbasart** [comment]
@hannahslee added you as co-owner of ticket for visibility

**Comment by aaronhans** [comment]
This seems outdated. I know several of these things have their own tickets now, some are done. 

Can we close this because we've already created tickets for everything still undone we still want @kenbasart or should I help link each of these items to the appropriate tickets so we can be sure?
