### ISSUE TITLE
Statewide metrics rendering incorrectly on iOS portrait -- What's Open page

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1632]
Statewide metrics show as "######" on the What's Open page when iOS mobile device is in portrait mode. Screenshots attached.

![IMG_0725](https://user-images.githubusercontent.com/69479727/92806797-2bcd0f80-f36f-11ea-9dc8-4b04d0997fd2.PNG)
![IMG_0726](https://user-images.githubusercontent.com/69479727/92806818-3091c380-f36f-11ea-8f3a-7c13ca8c171d.PNG)

**Comment by aaronhans** [comment]
This is interesting behavior. I wonder if tableau does this because the number might be getting obscured and they think hiding it totally might be better than showing it partially. 

We need to connect with slalom on this. They should be able to optimize this without any code change on our part. If they do want us to modify the embed code we will follow their instructions.

**Comment by aaronhans** [comment]
I am going to assign this back to @kenbasart for routing to the tableau team at slalom

**Comment by kenbasart** [comment]
@adam-little according to Aaron this is a Slalom/Tableau issue. Can you work with them to resolve this?

**Comment by adam-little** [comment]
I can not recreate this on my device (Safari on iOS). But I will send an email to Slalom.

**Comment by m-sullivan7** [comment]
Closing this issue as we no longer have this map on the site.
