### ISSUE TITLE
Newsreel pulling all Governor's Office press releases rather than Covid-specific releases

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1636]
Per @abquirarte : "longer term task. involves CDPH and GO."

cc: @hannahslee

**Comment by aaronhans** [comment]
FYI @kenbasart We are doing our own text filtering but we get a lot of false positives now because sometimes the string covid is present in a url linked in the summary. We could upgrade our parsing to focus only on the post title or filter out any HTML to make it more accurate. This might be able to be accomplished pretty quickly.

I don't see a priority on this ticket. It seems like a good thing to work on so I am assigning p1 but feel free to reset priority @hannahslee

**Comment by abquirarte** [comment]
i agree with Aaron
Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by kenbasart** [comment]
@aaronhans this was resolved, wasn't it?
