### ISSUE TITLE
Capture All Searches Done in Activity Status Search Bar

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1706]
Per @traintestbritt :

"As part of our continued Dimmer Switch research we'd like to capture what users are typing in the activity status search bar even if it's not in the list. I think I suggested that be None when we launched. Can we keep it as None if a user performs a search on their county and doesn't select an activity at all and then can we capture what a user types in if it's not a part of the activity status list in addition to continuing capturing what they select/enter if it is already on the list?"

cc: @hannahslee

**Comment by aaronhans** [comment]
To clarify:
- If a user hits the submit button after typing in an activity that we don't have info on we will record that as an event

This seems like a great idea because it can inform us of things we might want to include

What should the GA event look like in this case @traintestbritt ?

We are currently doing:

| Category  | Action | Label |
| ------------- | ------------- | ------------- |
| "activity-status"  | "county selected or empty"  | "activity selected"  |

I wonder how we could signify that these events are activities that the user typed in that we do not have info on

**Comment by m-sullivan7** [comment]
Closing this issue as this feature is no longer on the site.
