### ISSUE TITLE
Fix header layout bug on mobile

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#1901]
Menu icon breaks to a new line which results in the sticky header occupying a third of the screen height. Please fix so that menu icon/button is on the same line as language and search.

**Comment by adam-little** [comment]
Latest chrome app on iPhone SE 

![image](https://user-images.githubusercontent.com/69167298/94831374-803d3b00-03c1-11eb-92e2-a0586aee8a03.png)

**Comment by aaronhans** [comment]
There isn't much room at 320 width but if we hide the placeholder text in the search box maybe it looks alright

<img width="494" alt="Screen Shot 2020-10-01 at 8 49 18 AM" src="https://user-images.githubusercontent.com/353360/94833238-bed3f500-03c3-11eb-8ab9-9cd9ddfd9a69.png">

That screenshot reduces the width of the search box to make things fit but it is so small the icon is on top of the placeholder text if it isn't hidden

We'd need a missing smaller breakpoint to handle:
- reduced search box width
- hiding placeholder text
- making margin top on main less, down to at least 135px instead of 165

**Comment by aaronhans** [comment]
In terms of priority, I am trying to fit in the remaining P1s for state-dash since we have a scheduled QA event tomorrow morning.

This is a severe bug indeed but has been present since the new homepage redesign so I'll prioritize it after the P1 state-dash QA event. Let me know if that is not appropriate

**Comment by kenbasart** [comment]
+ @hannahslee see Aaron's comment re: prioritization

**Comment by aaronhans** [comment]
PR opened, linked above

Fix is in staging now @adam-little @koryfey

**Comment by kenbasart** [comment]
On staging/closing

**Comment by aaronhans** [comment]
Are we being too quick on the trigger @kenbasart? We have an open PR still which may not pass code review. Let's document the QA steps we perform as well. Messing around with media queries like this can create bugs in other screen sizes so I'd like to document what we've tested to verify this

**Comment by kenbasart** [comment]
Makes sense -- reopening.

**Comment by m-sullivan7** [comment]
I tested and it looks like our fix went through. Closing this issue.
