### ISSUE TITLE
Map is not full column width

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1929]
per @adam-little

**Comment by adam-little** [comment]
Since we use the same map on State Dashboard and Dimmer Switch, this applies to both pages. I am assuming the content column on both pages is the same (if it's not, it should be). 

**State Dashboard**

![Frame 31](https://user-images.githubusercontent.com/69167298/94968627-1f435f00-04b6-11eb-9e09-1a13af917b7b.png)
