### ISSUE TITLE
GET HELP, Health information, Working and How to Help Links are Misleading

### ISSUE THREAD

**Issue by kenbasart** [cagov/covid19#1951]
<img width="966" alt="Screen Shot 2020-10-04 at 7 48 46 AM" src="https://user-images.githubusercontent.com/4454420/95106198-0ec8f980-06ed-11eb-9f3b-5eb72bcb7680.png">
<img width="1032" alt="Screen Shot 2020-10-04 at 8 39 38 PM" src="https://user-images.githubusercontent.com/4454420/95106229-1a1c2500-06ed-11eb-8703-bffbbc94c244.png">

Per @clarita1980:

"The titles in the navigation (GET HELP, Health information, Working and How to help) behave like links and 65% of clicks on the navigation are on those titles. It's an interesting fact to know because it's sending the expectation that there might be a page with overall information but because we don't have that it's creating a bad UX. For now, it's recommended to make titles don't behave like links."

cc: @hannahslee

**Comment by thepegisin** [comment]
Suggest those section headers be orange, not underlined, and non-reactive to hover. Only links should look and behave like links.

**Comment by adam-little** [comment]
Here's a screenshot and Figma link for a suggested design. 

Key changes:

- Remove link and underline from section headers
- Make section headers sentence case capitalization (not all caps)
- Page links should not be bold
- Menu button label should read "Close"

![Main menu](https://user-images.githubusercontent.com/69167298/95259939-eed12d00-07f5-11eb-8194-ac6c5705b95f.png)

https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/covid19.ca.gov-screens?node-id=2088%3A11

**Comment by Mark-Tyler** [comment]
@kenbasart this is within the skills of Konstantin and not within mine. I would suggest setting this to him.

**Comment by kenbasart** [comment]
Ok will assign it back to him. Thanks!

**Comment by xjensen** [comment]
I saw this and wanted to clarify something, just in case. On mobile, those headers **do need to be links** because they trigger a pull-down menu. This isn't necessary on desktop.

Not expanded on mobile:
![headers](https://user-images.githubusercontent.com/1208960/95400149-c19c8180-08be-11eb-81e3-ab14d34734d8.png)

Expanded on mobile by clicking on the heading:
![headers-expanded](https://user-images.githubusercontent.com/1208960/95400166-c8c38f80-08be-11eb-9fb7-b8f08c246e54.png)

So this raises a couple questions. 

**One**, on mobile, clicks on those links would be quite valid. I wonder how many of the hits in the analytics are coming from mobile vs. desktop. 

**Two**, on the technical side, would it be preferable to just CSS away the link-interaction stuff at higher responsive breakpoints? Or do we need to display a whole separate snippet of HTML for accessibility purposes, etc.? I haven't thought this through yet.

Apologies if all of this has already been considered.

**Comment by abquirarte** [comment]
☝️ such a great point! 

cc: @adam-little @hannahslee @aaronhans

**Comment by aaronhans** [comment]
Really appreciate that insight @xjensen 

The task for this will be to change the user behavior only on large screens where those aren't really links so they:
- don't show clickable icon on hover
- aren't underlined as Peggy suggested
- we need to be careful that they still work as designed currently on mobile

**Comment by xjensen** [comment]
See PR #1985 for possible solution.

**Comment by xjensen** [comment]
This fix is now live.

**Comment by kenbasart** [comment]
Closing per Jon Jensen

**Comment by kenbasart** [comment]
Following up with @thepegisin re: status. Reopening.
