### ISSUE TITLE
IA Update to our homepage- it's losing its impact

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#215]
## context
when we launched 3 weeks ago, it was different times, and there was **much less** content. I think it's time for us to revisit our information architecture. So that we can plan for new incoming content. 
The sub-nav is also becoming super busy :) 

***Can we get PD and other experts/practitioners to give us their thoughts on this? It would be good to get outside view looking in perspective on this. See Corey's notes below***

**Output**: sketch/ouline
**Timeline**: early next week, if not sooner

### Considerations
We want to simplify the homepage, and are considering removing the “dos and don’ts” list in order to more quickly get users to the content they need. Can you help us draft up the categories and link content to get users to deeper content from the homepage (in other words, a simple user-facing IA/taxonomy). Categories we’ve talked about include “How to care for yourself and your family,” “How to help your community,” “Get help,” etc.
We need some help ensuring that all content fits in the homepage categories, and that they’re user-centered and flexible enough.

### IA Notes: https://docs.google.com/document/d/1SYQPmBNFjWtruABzQei1MpIIFIXzk8ddmhHzKaAUCGw/edit

**Comment by abquirarte** [comment]
Other suggestions (from GO)
-Health Information
-Economic Assistance
-Schools
-Help Others

**Comment by abquirarte** [comment]
Notes documented on this project board: 
https://github.com/cagov/covid19/projects/2

**Comment by staceyphillips** [comment]
Here are the mockups that Sarah shared on the call just now. 

<img width="591" alt="Screenshot 2020-04-14 at 20 01 07" src="https://user-images.githubusercontent.com/15262141/79263482-d1e12000-7e8a-11ea-8e24-847f72abb04f.png">
<img width="594" alt="Screenshot 2020-04-14 at 20 01 13" src="https://user-images.githubusercontent.com/15262141/79263487-d4437a00-7e8a-11ea-9f2b-c504e18b8fda.png">

**Comment by abquirarte** [comment]
@artuoma @thepegisin @hilaryhb @coreycaitlin 

Moving my sticky notes here. lol

- Up to date, 23% of the responses we have received through the feedback survey still ask: Is my [business/workplace/personal activity] essential or non essential." I think we should stage it as it's own page and make it more clear/direct on the main page. 
- There seems to be a need for a visual representation of our impact/the impact. Could be addressed by Art's issue on Latest numbers: https://github.com/cagov/covid19/issues/291. Essentially, "Where are we flattening the curve?" 
- action and result (vs. enforcement). In an earlier iteration we had toward the top that the virus spreads even if you don't feel it. (screenshot below) 
![](https://files.slack.com/files-pri/TQ4HKJEQP-F011RCBDU06/screen_shot_2020-03-14_at_3.42.41_pm.png)
- Overall more clear, active voice. Standardize grammar across the pages. 
- Better search, at least more engaging way to find info. (in progress)  https://github.com/cagov/covid19/issues/152
- Better SEO (in progress) https://github.com/cagov/covid19/issues/290
- Move icons up (?) Track which content falls in which category
- Make the most of the latest news/ information- people want to know. Daily banner + latest news section 
- Move the public places questions to the Stay home FAQ. 

my terrible sketch 😅 

![](https://files.slack.com/files-pri/TQ4HKJEQP-F011SCVGFJS/20200416_082657.jpg)

**Comment by abquirarte** [comment]
![20200416_082657](https://user-images.githubusercontent.com/9556188/79672035-30581800-8183-11ea-844f-3e11f265a8d0.jpg)


![20200416_082657](https://user-images.githubusercontent.com/9556188/79672050-4d8ce680-8183-11ea-9ad7-9ae9357f942d.jpg)

<img width="1245" alt="Screen Shot 2020-04-14 at 5 26 52 PM" src="https://user-images.githubusercontent.com/9556188/79672067-9f357100-8183-11ea-8ec0-aecffc7cb2ed.png">

**Comment by abquirarte** [comment]
https://cadotgov.slack.com/files/UQVAKTF7Y/F012ANXBE1X/screencapture-as-cdt-pub-acovid-w-p-001-staging-azurewebsites-net-2020-03-14-18_18_35.png

**Comment by abquirarte** [comment]
![screencapture-as-cdt-pub-acovid-w-p-001-staging-azurewebsites-net-2020-03-14-18_18_35 (1)](https://user-images.githubusercontent.com/9556188/79672171-85485e00-8184-11ea-8cb5-d351b609863e.png)

**Comment by abquirarte** [comment]
![image](https://user-images.githubusercontent.com/9556188/79672484-3ea83300-8187-11ea-92b1-4e61a677a135.png)

**Comment by thepegisin** [comment]
Here is what I propose for a revised sitemap/IA:
([https://docs.google.com/document/d/1gV5ePZl49kfmxOBFyPYX53wuDOIa3_qB34Eb5KGlnQA/edit#heading=h.xgq8keso58os])

**Comment by coreycaitlin** [comment]
This is a lot of options and ideas! I think the most crucial thing is to dramatically simplify the page and get people to the content they need faster, which will mean making some tough decisions.

Fundamentally, this site is doing three core things:

1. Providing a directive: "stay home" [except for etc etc.].
2. Offering services and information about what people can do about it.
3. Giving information (and reassurance) about what the state is doing.

Each of these is really important, but they're currently a little intermingled in a confusing way. After looking through the recommendations posted above, I think I agree with both Lande's doc and Sarah's sketch that we need to break down the action-oriented lists into _slightly_ more granular groupings. (I.e. splitting "what you can do" into "health info," "economic help," and others.)

I'm going to take a little time to markup the current homepage visually tomorrow morning, but here's my quick list of recommendations that I think we could implement as a first iteration *without* other pages really changing, and that would solve some of the category bloat while setting us up to keep iterating on the homepage:

- Keep the Stay Home order language on top
- Move all services/info links up to just below the “what’s new” banner, and divide them into more natural groupings, including something like:
	- Staying healthy and getting care
	- Get economic help
	- How you can help others
	- Other government services (ed, taxes, etc.)
- Remove Do/Do not section (the list is feeling kind of arbitrary at this point; if any of the content in this list is _not_ on other pages, we can move it there)
- Consolidate latest numbers + "round the clock" + latest news into one section that is clearly “What’s up in CA”
- Nix all “services and info” cards because all key links have moved up
- Choose EITHER latest news OR “what’s new” banner above; they’re redundant. I'd always vote for the one that doesn't have to be manually updated, but either could work.

I think @thepegisin's doc gets more into the details of what the actual link language should be for many of these links, as well.

**Comment by coreycaitlin** [comment]
Okay, I spent some more time this morning thinking through the details of which link goes in which [new] section, since that seems to be the spot where the devil's in the details. [Put it in a spreadsheet here](https://docs.google.com/spreadsheets/d/19xWXggoQ2dKNGw27LQ3_kKbkpfHsWtvENHqSVEE48-g/edit#gid=0); it definitely needs some more love on copy (esp. deciding if we want parallel structure, and implementing it), but should offer a little more clarity on where everything would go.

**Comment by coreycaitlin** [comment]
Thanks for adding the new pages to the spreadsheet @abquirarte! I've taken a stab at naming the categories for each, though I'm definitely making some assumptions about what the pages will include, so I may be off-base.

I think the stickiest outlier pages are the ones _for_ specific populations, and might merit their own category — something like "Resources for..." It could include links like:

- Guide for immigrants
- Housing for healthcare workers

I'm not sure about this, but I think it's worth considering.

**Comment by abquirarte** [comment]
Thank you! 
- I was wondering if healthcare workers should be part of Health corps, or housing?
- Would be good to talk through these new pages. Child care page will have a similar tone. It will go live by the end of the week (likely), food is going live Friday. 
- We also have the anti-discrimination page

I was thinking of those in the lens of "community" 
But broad "Resources" landing page could work... 

---------- from an earlier IA draft

Homepage
Stay home except for essential needs
- Executive Order (PDF)
- Stay home FAQ with public places content
- Essential needs

Get help
- Get food
- Get financial help
- Get basic needs
- Apply for unemployment (PUA)

How you can help

- Health Corps
- Volunteer (link out)
- Support a non-profit (link out)
- Offer supplies and contributions (link out)
- Submit tech solutions (link out)

Other services:

Housing
- Homelessness 
- [Part of Get financial help content]
- Eviction
- Relief from financial institutions

Health and Safety

- Know symptoms & risks
- Get testing and treatment [add Q&A about testing/treatment capacity, etc.]
- Health care
- Telehealth 
- Emotional health resources
- Stress playbooks

Education and Childcare

Economy

- Businesses and employers [Employers content + new small biz content]
- Workers [Employees]
- Taxes
- Get help for small businesses (link out)
- Employment and taxes [redirect to Businesses and employers]

Communities Get local information
- Local information
- Sign up for alerts 
- Anti-discrimination 
- Immigrant guide

**Comment by coreycaitlin** [comment]
I've beefed up [this spreadsheet](https://docs.google.com/spreadsheets/d/19xWXggoQ2dKNGw27LQ3_kKbkpfHsWtvENHqSVEE48-g/edit#gid=0) to provide a more complete sitemap with current vs. proposed link text...and instigated some Slack polls about finalizing the names of the categories. 😎

**Comment by coreycaitlin** [comment]
And here's a marked-up version with annotations:

![Untitled_Artwork](https://user-images.githubusercontent.com/1450354/80111775-2a708700-8535-11ea-9107-4208fd68877d.png)

**Comment by coreycaitlin** [comment]
Per #341, it sounds like the do's and don'ts list is still proving useful to folks! If we do keep it, we should edit it down and make it more current. Here's one stab at updating it:

Do:

- Stay home
- Stay at least 6 feet away from people outside your household
- Cover your mouth and nose when you go out
- Wash your hands often
- Get support online or over the phone

Do not:

- Leave the house except for essential activities
- Touch your face
- Shake hands or hug people outside your household
- Go to the doctor or hospital (unless you call first)

**Comment by hilaryhb** [comment]
Do you think we need the shake hands/hug at this point? I feel like with the stay 6 ft away above really gets to this? 

And I appreciate the get support online/phone - but feels too ambiguous, do we mean financial support? mental support? feels less crisp/clear than other do's...

**Comment by thepegisin** [comment]
Strongly agree with the user feedback that Do's and Don'ts should stay. Try to keep them parallel, max 6 bullets each (less is better). Here's my edit:

Do:
- Stay home
- Wash your hands
- Disinfect things you touch
- Keep 6 feet from others if you must go out
- Wear a mask outside your home
- Connect with friends online or by phone

Don't:
- Leave home for non-essential activities
- Touch your face
- Go to the doctor without calling first
- Stockpile masks or gloves
- Share bad information
- Stigmatize others

**Comment by coreycaitlin** [comment]
After some discussion and feedback in Slack, it sounds like we should name the main 4 categories like so:

1. **Health information**
2. **Get financial help** [*with the knowledge that this section is likely to split into 2-3 sections in an upcoming iteration]
3. **How you can help** OR **Give back** [let's see how each works in the design; they're different enough in length that it may be nice to have 2 options to play with]
4. **More services and information**

There were also some good notes about what belongs where, which I've integrated into the [spreadsheet](https://docs.google.com/spreadsheets/d/19xWXggoQ2dKNGw27LQ3_kKbkpfHsWtvENHqSVEE48-g/edit#gid=0)

@thepegisin Let's find some time to chat this evening to align on a shared recommendation for the dos/donts language?

**Comment by coreycaitlin** [comment]
Yay! @thepegisin and I paired on the do's and don'ts language. We decided to keep this list focused on baseline dos/don'ts for flattening the curve (aka the relationship between you and the disease), and cut anything that's a little further removed.

Do:

1. Stay home
2. Limit essential trips as much as possible
3. Stay at least 6 feet away from people if you must go out
4. Wear a mask outside your home
5. Wash your hands
6. Disinfect things you touch

Do not:

1. Leave home for non-essential activities
2. Touch your face
3. Go to the doctor without calling first
4. Stockpile more than you need
5. Spread rumors or share bad information

I'll re-markup the current homepage this evening to integrate @hilaryhb's user feedback notes and reflect that we're keeping the dos/don'ts.

**Comment by coreycaitlin** [comment]
Another "mockup" with my chicken scratches:

![Untitled_Artwork 2](https://user-images.githubusercontent.com/1450354/80287768-11f49e00-86e8-11ea-8eb3-9543ce092104.png)

Changes include:

- Moving GO links to "news" section instead of numbers section
- Keeping do/don't lists
- Putting "How you can help" category last among the 4 link sections

I'm concerned that we have too many banner-type things happening at the top now...is there some way to pull some of those sections (Stay home, numbers, and news) into a more compact or parallel design? As I [mentioned above](https://github.com/cagov/covid19/issues/215#issuecomment-617539981), the page is trying to do three things (1. Directive; 2. Services; 3. State action/status), and we're intermingling those things across the page like so:

1 [Stay home]
3 [Numbers]
3 [GO news]
2 [Services + info]
1 [Do / Don't]
3 [CA action]

I think the ideal would be to pull like content together with like as much as possible, but this would mean disturbing the order of banners at the top. If that's not feasible given communication priorities, I think we can move forward with this mock and address it in a later iteration.

**Comment by artuoma** [comment]
This is really good! I can try to make this organization move visual and if we like the categories we I can also start working on the landing pages to break our website up more.

**Comment by KaylaPrusia** [comment]
Question re: DMV services is now live on the stay home FAQ page to help with the removal of the public places page.

**Comment by hilaryhb** [comment]
@coreycaitlin @thepegisin @abquirarte which is the latest proposed do and don't - we want to test it w users

**Comment by abquirarte** [comment]
> @coreycaitlin @thepegisin @abquirarte which is the latest proposed do and don't - we want to test it w users

I believe this was it: https://github.com/cagov/covid19/issues/215#issuecomment-619253676

**Comment by abquirarte** [comment]
**Requests from GO documented here:** https://docs.google.com/spreadsheets/d/1UerlFWokTC8jf7ryXbDb_wksgRq15sLGuqzuD0Ng_6s/edit?ts=5ebf27ee#gid=0

**Comment by TamaraIDEJA** [comment]
### What to do

Your actions save lives. 
We can all help control the virus if we all stay alert. This means you must:

- stay at home as much as possible
- work from home if you can
- limit contact with other people
- keep your distance if you go out ( Stay 6 feet apart)
- wear a face covering 
- wash your hands regularly
- do not leave home if you or anyone in your household has symptoms

### Where CA is with reopening (What's Open/Whats Not - Navigation or Dynamic Sears - Q&A)
What I should do - PPE masks 
Resilience Roadmap 
County Variance
Recovery input 

### Get Help 
Get  Financial help 
Business +Employers
Housing + Homelesness 
Workers
Taxes
Manage stress playbooks
Guide for Immigrants 

### Get Healthy 
Symptoms and Risks
Contact tracing 
Testing and treatment 
Healthcare
Telehealth

### Services (or combine with Resources)
Find Childcare 
Great Plates Deliver 

### Resources 
Get Food 
Emotional support 
Local Resources and alerts 
Education 
Public Recreation 
Hotels for healthcare 

### How you can help or Give Back
Plasma donation 
Healthcorps
Volunteer in 
Check in elder CA
Support non profit
Offer supplies
Tech solutions 
Fight discrimination 
Restaurants form 

### Information 
Hotline
Toolkit 
Contacts

**Comment by abquirarte** [comment]
From inspiration above ☝️  and what the team has prototyped I am thinking of a few changes to the structure we tested. It's not drastic, but hopefully it clears things up a bit. 

## Prototypes:  https://drive.google.com/drive/folders/13ttsFaOhlwnT50DXlmfxk8SdvVC1bQ9C 

## Former outline: 
![20200519_161116](https://user-images.githubusercontent.com/9556188/82941469-4065d300-9f4b-11ea-986d-b926493834fe.jpg)

## Proposed

### Get Help
Get financial help
Find childcare
Guide for immigrants 
Get food 
Emotional Support
Manage stress 
Workers 
Business and Employers 

### Health Information
Symptoms and risks
Testing and treatment
Contact tracing 
Health care 
Masks and PPE 

### Information and Resources 
Local resources + Alerts 
Education
Public Recreation 
County Variance
Roadmap 
Industry Guidance 
Contracts 
Hotline 
Taxes 
Housing and homelessness 

### How you can help
Health corps
Plasma donation
Fight discrimination 
Restaurants form
Recovery survey 
Volunteer 
Check in on older CA
Tech solutions 
Toolkit (Spread the word)

**Comment by abquirarte** [comment]
Closing this. Next iteration will be new issue. Focus will be on count/roadmap content.
