### ISSUE TITLE
Consolidate buttons in homepage 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#255]
Lande pulled together content so we can consolidate the links in the “how you can help” tab into two pages so we don’t have to keep adding buttons with every new external resource. 

Below are her comments for our review. 
#### State of California COVID-19 Technology Solutions
Please visit tech.covid19.ca.gov to submit COVID-19 response technology solutions to the State of California. 
The State of California is seeking innovative technology solutions that help support the COVID-19 response. This is a unique opportunity to share your solution with state officials.
State of California COVID-19 Medical Supply Contributions
Please visit covid19supplies.ca.gov to offer medical supply contributions to the State of California. 
Use this form to describe resources you have to contribute, either for donation or purchase, to support California’s response to COVID-19.

#### Volunteer in Your Community
•	Deliver meals
•	Donate to a shelter or food bank
•	Volunteer at a Food Bank
•	Donate blood
•	Learn about ways you can make a difference on the California Volunteers website.
#### Stay Home. Save Lives. Check In.
•	Call, text, and (safely) knock on doors to make sure our neighbors, friends, and family are connected and have the support we all need! 
•	Use this Community Check-In Checklist, then share it with at least five people you know.
•	Learn more about the Stay Home. Save Lives. Check In. campaign on the EngageCA website.
#### Support a Non-Profit
Visit the Philanthropy California website to find Response Funds across the state.

**Comment by abquirarte** [comment]
@artuoma I think like the support your community consolidation of pages. What do you think? 
cc: @thepegisin @hilaryhb

**Comment by thepegisin** [comment]
Circling back to this, as I think I missed it when you first posted it. My feedback:

- Turning these individual topics into just two pages would effectively hide them. Our current path is more enticing and personal: **[You can help] --> [This way might appeal to you]**.

- **Support Your Community** is too vague and mushy. What if you already do? **COVID-19 --> You can help --> Thing** is much more direct and appealing.

- **Assist the State** is distinctly not appealing. It's not the State folks are trying to help, but each other. When you center the State, or a department, or bureaucracy, you lose the user's interest and goodwill. They want to help the equivalent of someone who's fallen and needs help getting up.

I think instead of putting another layer of category between these help topics and the reader, we should retire links from the menu that are old, outdated, little used, or not on our site. We can find plenty of those!

**Comment by abquirarte** [comment]
Yeah I think this is no longer an active issue or problem we need to solve for now that we have a navigation. Yes on thinking through what pages need to continue to exist within our flat nav. If we keep adding pages, we may need to have something more hierarchical or simply just have as part of our improved search!

Closing issue for now :)
