### ISSUE TITLE
Dev Priorities

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#28]
Staging --> Production process 

https://docs.google.com/document/d/18lZTpeqpGvh0wp7883H-gxt2U_DvxDWOVUPCL4cHMcs/edit?usp=sharing

**Comment by tallguyjenks** [comment]
suggestion? taking advantage of the wiki feature on repo's for documentation?

it enables collaboration, version control, & local editing of the information so everything is in one place?

https://help.github.com/en/github/building-a-strong-community/about-wikis
https://help.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github

**Comment by abquirarte** [comment]
@tallguyjenks awesome! We've been moving so fast we are not keeping up with documention. @aaronhans had just made some updates. 😄

**Comment by tallguyjenks** [comment]
this way you can keep track of changes with commit history, and you can use markdown instead of [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG) editing in googledocs/word :smile: 

im building all the documentation infrastructure for my agency's development team, if theres some way i can help please let me know:exclamation:

**Comment by aaronhans** [comment]
The priorities in the attached doc have all been completed or translated into github tasks in this project if they are still relevant
