### ISSUE TITLE
Add supporting visual elements to the Latest Numbers section

### ISSUE THREAD

**Issue by artuoma** [cagov/covid19#291]
Need a way to represent latest numbers more visually.

**Comment by artuoma** [comment]
@abquirarte Can you please share what Mike sent you as examples of this?

**Comment by aaronhans** [comment]
https://coronavirus.data.gov.uk/

**Comment by abquirarte** [comment]
@artuoma Mike has not shared anything yet. UK example is a great start!

**Comment by abquirarte** [comment]
Need to propose design by the end of the day today. 
Due: tomorrow at noon. 

- Move up latest numbers. 
- Figure our language that will link to this more visual representation of the numbers. 
https://slalom.invisionapp.com/share/QBWXD4F4F75#/screens 
- We have to keep the dashboard links.

**Comment by thepegisin** [comment]
My recommendations: https://docs.google.com/document/d/1wp3ne1KwThb1hkC9mRky03wONYV4yGi2Ks5VwlcEuMM/edit?usp=sharing
Let's beat on this.

**Comment by abquirarte** [comment]
@artuoma @aaronhans @coreycaitlin 

The design below was 👍 by GO. I think it needs some cleaning and we need to make sure it is mobile friendly. Maybe make the numbers smaller? 

Timeline, be ready in staging by tomorrow noon. 

- [ ] Clean up design
- [ ] Link will be: update.covid19.ca.gov 
- [ ] How does this affect the translations and updates? I worry more design creates more design/translation debt for us. @aaronhans 

<img width="1255" alt="Screen Shot 2020-04-23 at 7 02 01 PM" src="https://user-images.githubusercontent.com/9556188/80174950-16666d00-85a9-11ea-8cfc-baff996e3cd5.png">

**Comment by aaronhans** [comment]
The new layout looks great in staging already @artuoma!

In order to ship this in multiple languages we can utilize the existing WordPress fragments. We can ship a custom HTML block or we can transition it to json by:

- Putting the column headers and values in a table block element in WordPress
- adding the "table-data" tag to the post
- Putting the surrounding HTML in an 11ty template that consumes the json created from the post at build time

It is a little faster to do the HTML in WordPress first as a custom HTML block so if we need to we can ship that first and transition to table-data powered json later.

**Comment by artuoma** [comment]
@aaronhans For translations they can just have the simple text version. Another option is to have HTML into WP. Not sure how long this section will last as a manually maintained section so not sure any custom development is worth it.

This is my recommendation, all other languages receive simple text version. A list and a link.

**Comment by abquirarte** [comment]
done
