### ISSUE TITLE
Design- new way to display content in Essential Workers PDF 

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#311]
## Context
Ever since the stay at home order went into place, we have done what we can to ensure that our content is clear. This is complicated content. From go live until about a week ago 23% of entries in our user feedback survey documented questions around what is essential/not. 

We have the opportunity to rethink/redesign how we display this content in a clear and accessible way. We need to follow our [crisis standard. ](https://github.com/cagov/covid19/wiki/Crisis-standard). 

👉  [draft of content](https://docs.google.com/document/d/1ISBfBK74s87PZqOg8xlhuJwEMvoElJnD/edit)

**Examples (some good, some ok)**
- Colorado: https://covid19.colorado.gov/stay-home-except-essential-needs
- UK: https://www.gov.uk/guidance/social-distancing-in-the-workplace-during-coronavirus-covid-19-sector-guidance
- Washington: https://www.coronavirus.wa.gov/whats-open-and-closed/essential-business
- NY: https://esd.ny.gov/guidance-executive-order-2026
- NJ: http://ready.nj.gov/programs/essential-employees.shtml OR https://covid19.nj.gov/search.html?query=essential+business+list
- CISA https://www.cisa.gov/identifying-critical-infrastructure-during-covid-19

### Timeline
COB Tuesday 4/28. It should align with our translation work and re-design of homepage

- [ ] Go through draft content and document in a spreadsheet the sectors, what is open, what is not, what is essential, summary sentence of what it is.

**Comment by hilaryhb** [comment]
@abquirarte do you want us to edit the "draft of content doc"? how much can we edit down or make it straight forward?

**Comment by abquirarte** [comment]
> @abquirarte do you want us to edit the "draft of content doc"? how much can we edit down or make it straight forward?

Yes please! We'll need a way to keep track of changes. @coreycaitlin @thepegisin how do you think we can tackle this?

**Comment by abquirarte** [comment]
Talked to the Digital team in NJ. They turned theirs into a spreadsheet and leveraged (yext) search can determine weather something is essential/open/not.

**Comment by coreycaitlin** [comment]
Yeah, that seems like the right approach, and would allow us to provide synonyms so people can use their own language and find the right answers.

**Comment by thepegisin** [comment]
I started a spreadsheet, consulting with @aaronhans on what the column headers would be. The idea is that this data would drive a search result like this one from NJ: https://covid19.nj.gov/search.html?query=doctors+open

So far, I've made it through Healthcare sector. Here's the spreadsheet: https://docs.google.com/spreadsheets/d/1ChCtNZT8lwqNBumJo9Js-VcR_4Ra47nMGbZDVbizT-4/edit?usp=sharing

**Comment by thepegisin** [comment]
After trying to turn this list into a db, I had some thoughts about the problem of sharing essential jobs info in a consumable way. 

**Short version:**
Let's just give a plainspeak description of the essential job categories, so people can determine for themselves whether their job belongs in one. If they need more info, they can click through to the longer list. Here's my draft of that: https://docs.google.com/document/d/13dwKzlWZWf5VI7eq3NE0Tnkn1ccb-iXQ4qp2l_HHqMI/edit

**Long version:**
The task of taking all the job titles in that document and putting them into rows in a database is a massive one. It took me 3+ hours to get through 1/8th of that document. But even if we did it, that wouldn’t solve the problem.

1. We only have essential job titles. We don’t have non-essential job titles. So if someone enters a non-essential job title, they don’t get an answer. That could be the majority of our searches. 

2. Job titles can vary wildly. Janitor = sanitarian = facilities engineer. So someone’s job could be in the db, but they may not find it. We can’t possibly come up with all the synonyms for all the jobs. 

3. **I suspect the people who need to look up what jobs are essential are those that are in a gray area, and who need a ruling.** Example: an optician supports the work of an optometrist, and the optometrist can't open their office without an optician. But opticians aren't listed as essential. So they wouldn't find themselves in our db.

People don’t need a lookup for every job title. They need the data interpreted. Put into brief, simple terms. 

Instead of 90 different healthcare job titles, say, “If you’re a medical doctor, nurse, hospital worker, medical support staff, or work in hospital administration, you’ve got an essential job.”

Make the list into jobs buckets that are short and scannable. “Hospital workers and administration” covers a huge amount of jobs. People know if they do or don’t fit. 

If we attack the problem in this way, we could probably have a useful list up in about a day. And for those who need more granular data, we’d have a link to the PDF.

**Comment by abquirarte** [comment]
Closing this for now. I think we may be past this. Search would help.
