### ISSUE TITLE
Upgrade global hamburger menu to ribbon that shows menu names

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#4979]
We've wanted to do this for a while and there's no reason not to get it done now.

![Menu 3](https://user-images.githubusercontent.com/69167298/131573651-f575f734-82c7-4adf-ad9a-83145329d445.png)

**Comment by adam-little** [comment]
@aaronhans Can you review the attached screenshot and let us know how much work you think this is?

Search and language picker would behave same as current COVID website, but would have the styles of the design system.

Note that I am using Roboto instead Public Sans so that the font matches the rest of the COVID 19 website.

**Comment by aaronhans** [comment]
This is fantastic @adam-little!

I think there are a couple days of development work here to get the old header swapped out and all these elements working using the new components on desktop and mobile

**Comment by adam-little** [comment]
Here are updated designs:

https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/COVID19.ca.gov-screens?node-id=7983%3A37720

Desktop:
- Please use same dropdown style as the COVID19 language picker dropdown
- Font size for menu items are 19.2rem (same as P)

Mobile:
- No changes. Continue to use hamburger menu as is.

**Comment by mediajunkie** [comment]
please let @adam-little or @mediajunkie know if you have any questions

**Comment by zakiya** [comment]
@adam-little  Do you want the ribbon menu to be fixed on scroll along with the main header?

**Comment by adam-little** [comment]
Good question. Yes, can you make the ribbon fixed? Then we can evaluate whether or not it has a negative impact on available screen real-estate for page content.

**Comment by zakiya** [comment]
@adam-little @mediajunkie Does the site have a philosophy for hover and focus states?

**Comment by mediajunkie** [comment]
Great question! I'd defer to @adam-little on that, especially for what we have been doing up to now. 

Adam, is this something we have a clear point of view on in the covid19 site design? If not, maybe we can come up with a working approach for the time being, If so, is it captured somewhere (or in specific examples)? If not, we can make note of it, somehow.

**Comment by zakiya** [comment]
Using this comment to track my @todos and notees. I will update it as I make progress. 
- verify breakpoint where layout changes
- hover/active/focus
- Remove hamburger from large screens
- Check body position on interior pages.

**Comment by adam-little** [comment]
@zakiya Good question (again). Sorry for not providing this documentation up front.

Generally on COVID we use underlines for hover states and borders for focus states.

[Here's where you can see](https://www.figma.com/file/LrzsOu8U5KcMAjJTQ1O3BG/COVID19.ca.gov-screens?node-id=4591%3A16844) various button and link states for COVID. I added a section for the ribbon menu and the menu dropdowns.

![image](https://user-images.githubusercontent.com/69167298/136261532-c5978f00-f948-441e-8242-4ff7d82551d1.png)

**Comment by zakiya** [comment]
@adam-little Latest is up for review at https://nifty-turing-0ad445.netlify.app/ Let me know if I missed anything or if there are any changes.

**Comment by adam-little** [comment]
Looks good to me. Thanks, Zakiya!

@mediajunkie - Zakiya raised a concern that requiring a click to expand the dropdown may negatively impact discoverability. As you know, improving discoverability was one of the reasons for transitioning to this style of menu. Alternatively, showing the dropdowns on hover (instead of click) may improve discoverability.  But we opted to follow the same approach as the design system with the assumption that we will eventually test and validate that approach across all design system websites. Just FYSA.

**Comment by zakiya** [comment]
Assigning to @mediajunkie until further work is needed. Let me know if you ever want/need the Netlify environment updates with latest content.

**Comment by zakiya** [comment]
This is done and on production!
