### ISSUE TITLE
Replace hero image with one with face coverings

### ISSUE THREAD

**Issue by mediajunkie** [cagov/covid19#5006]
- [x] Ask for source images from RS-E
- [x] Choose new image
- [ ] update hero

**Comment by adam-little** [comment]
Consensus is to use "selfie" image because it shows people wearing a mask with a positive attitude and it can be interpreted as being indoors. 

This photo also works best compositionally for web and mobile.


![image](https://user-images.githubusercontent.com/69167298/128745950-ddad80a8-457f-40ed-958d-5413dc79bc46.png)

**Comment by jaredwyee** [comment]
@jbum this is workable. we haven't heard any pushback (or comment) from GO.

**Comment by jbum** [comment]
Done
