### ISSUE TITLE
Workers and businesses: add "more help" buttons

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#5041]
Use buttons for more help similar to those on the Get financial help page

[DRAFT EDITS](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)

**Comment by LizNobriga** [comment]
Ready for review in [staging](https://staging.covid19.ca.gov/workers-and-businesses/#worker-benefits).

![morehelp](https://user-images.githubusercontent.com/58706834/128764322-b8177430-0839-42a1-bdeb-d6a7ad93955e.png)

**Comment by m-sullivan7** [comment]
The links look good! I know that we don't usually center H3s, but _More help_ looks a little awkward left-justified. Maybe we could get Adam's opinion on whether it's OK to break with our usual formatting in this case?

**Comment by LizNobriga** [comment]
Hi @adam-little. We are thinking about using button links under an H3 on the **Workers and businesses** page. Could we get your opinion on whether to keep the _More help_ H3 left-aligned or if it would work better to center it?

**Left-aligned:**
![image](https://user-images.githubusercontent.com/58706834/128771592-c46c9b83-0f2c-4383-8757-da34ba01a287.png)

**Centered:**
![image](https://user-images.githubusercontent.com/58706834/128771511-8c52b550-a645-4122-bd67-9d9965b1d1cd.png)

**Comment by adam-little** [comment]
I would left align it. I realize that it looks wrong because the container with the buttons has space around it, so the buttons are not left aligned with the rest of the content.

But that bothers me less than having a title suddenly become centered.

Alternatively, you can put the buttons in a container with a background color and give it a centered H2. We can hide the H2 from the page index.  That would be similar to this container on the Vaccine page:
![image](https://user-images.githubusercontent.com/69167298/128915855-1676862c-cba2-493d-a02f-d96d92074c07.png)

**Comment by LizNobriga** [comment]
@mediajunkie This is ready for your review in staging: https://staging.covid19.ca.gov/workers-and-businesses/
[(see edits in google doc)](https://docs.google.com/document/d/1NbYh1TnzBV7uDh-6SUXpWD0YbkBc1TWwLeL9yId8sqM/edit#)

**Comment by LizNobriga** [comment]
Approved via slack. This is now published.
