### ISSUE TITLE
Fix spacing of content on Vaccine page

### ISSUE THREAD

**Issue by adam-little** [cagov/covid19#5067]
When a content block has a background color, then it should not have the horizontal rules (separators) above or below.

Can we remove the horizontal rules that appear above and below the color-filled content blocks on the Vaccine page?

Example 1: 
![image](https://user-images.githubusercontent.com/69167298/128915094-6a97254d-fb16-4004-9848-9424dd096a2b.png)

Example 2:
![image](https://user-images.githubusercontent.com/69167298/128915132-9d937d16-d903-4483-b592-8f22300d26cf.png)

**Comment by thepegisin** [comment]
@adam-little @mediajunkie This fix is published. I had to get very cutesy with hiding anchor tags in unexpected places, since I couldn't add them to separators. Hope this passes accessibility checks and looks alright on browsers and phones other than mine. But the separators before and after colored blocks are removed. Will find out where to document this so we know how to do it in the future.
