### ISSUE TITLE
Update "Find a testing location" link

### ISSUE THREAD

**Issue by thepegisin** [cagov/covid19#6055]
Kristina Keller from the My Turn team emailed to let us know that testing will soon be available on the My Turn site, and that we should update our "Find a testing location" link to go to https://myturn.ca.gov/testing. 
- [x] Draft change to _Testing_ page: https://docs.google.com/document/d/18NG21vDRhqR4Y795Mi1ibYhcuJd1F_EGHiVJKIZrKyo/edit
- [x] Hold until My Turn adds this functionality, likely by 2/4/22

The new link is live (https://myturn.ca.gov/testing.html), but it has many problems. You can't make a testing appointment through this search, or see if they accept walk-ins, or see hours of operation, or see any contact info like phone number. The address info is incomplete - just the house number and street, no city. The "Learn more" link doesn't take you to more info, it just puts you back on the My Turn homepage. So you can't book an appointment, and you can't see when or if you can walk in, you can't call, and you can't learn anything more. 

I recommend not adding this link until these problems are addressed. But if they make us use it:

- [ ] Stage
- [ ] Check
- [ ] Publish
- [ ] Check

**Comment by m-sullivan7** [comment]
Link is live and I've noted a second place it needs updating on _Mega-events_. I don't think that's urgent, so I've assigned it to Liz since she's the regular content captain for that page.

@mediajunkie Would you like me to update the thread or would you like to handle since you've handled the communication with them thus far?
