### ISSUE TITLE
Small change to plasma page 

### ISSUE THREAD

**Issue by TamaraIDEJA** [cagov/covid19#729]
### Content Update 

SME requested a small change to the plasma webpage – substituting word “**Some” for “Most”** – in bold below for ease of reference.

Who can donate COVID-19 plasma?
·         A person who had a test that showed coronavirus infection, 
AND
·         Has felt well for at least 14 days, 
AND
·         Passes the usual rules for blood donation. 
**Some** blood centers require a negative swab test if you plan to donate before one month has passed since you recovered. The blood center may also have other rules.

### Content Captain 
@JasonKarim 

### Timeline 
COB today

**Comment by JasonKarim** [comment]
### This section was revised last week, based on SME recommendation, to address change suggested in this issue along with few other changes, as follows:

[**Who can donate COVID-19 plasma?**](url)
A person who had a test that showed coronavirus infection
AND
Has felt well for at least 28 days*,
AND
Passes the usual rules for blood donation. 

*If you want to donate before one month has passed since you recovered, please check with your blood center. **Some** centers will require a negative swab test, and may have other rules.
