### ISSUE TITLE
Content clean-up suggestions- county variance page

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#734]
Content clean up **suggestions** from GO/GoBiz. Only stage if they make sense. 

- Casinos - In that paragraph “Casinos” is capitalized. Checking if intentional
- Hotels accordion title: Hotels (for tourism and individual travel) – should the paragraph inside illustrate short term rentals?
- Zoos and Museums – should probably include galleries and aquariums somewhere.
- Cardrooms and racetracks – paragraph in accordion may need to illustrate satellite wagering locations in the body.

**Comment by ashleydraper** [comment]
- [ ] Casinos - In that paragraph “Casinos” is capitalized. Checking if intentional

- [ ] Hotels accordion title: Hotels (for tourism and individual travel) – should the paragraph inside illustrate short term rentals?

- [ ] Zoos and Museums – should probably include galleries and aquariums somewhere.

- [ ] Cardrooms and racetracks – paragraph in accordion may need to illustrate satellite wagering locations in the body.

**Comment by ashleydraper** [comment]
Done and noted in [github issue #736](https://github.com/cagov/covid19/issues/736)
