### ISSUE TITLE
Workers page improvements

### ISSUE THREAD

**Issue by LizNobriga** [cagov/covid19#782]
[staging doc](https://docs.google.com/document/d/1iW4grIBD9wEnG7l5-lCoDSrBHPwdOTmyUK63HBq9hww/edit#)

- [x] Add links for support for working families pdf
- [x] Add link to childcare page
- [x] Move Hotel rooms for California healthcare workers to a separate page, no accordions, link on Workers page for more info
- [x] Add info/resources for employees for Families First paid leave

**Comment by LizNobriga** [comment]
@thepegisin tagging so you can see where it's at since our last discussion.

**Comment by LizNobriga** [comment]
@KaylaPrusia tagging since it will point to childcare page.

**Comment by LizNobriga** [comment]
@abquirarte thoughts on having "hotel rooms for CA health care workers" as a stand alone page with redirects?

**Comment by abquirarte** [comment]
I'm wondering how the redirect will work from workers to the new page since
we are only moving part of the content on that page into its own. Wouldn't
we address the topic prominently in the workers page and just point to the
new page?

For example we are linked to here:
http://caltravelstore.com/ca-healthcare-workers-lodging

I'm good with moving it to its own. Just want to make sure we let OES know.
:)

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
Yes, makes sense!

**Comment by LizNobriga** [comment]
All edits are live, except for hotel rooms - waiting until new page is confirmed.

**Comment by LizNobriga** [comment]
Removed accordions and content from Workers page (new Hotels page is live and linked from this page)

**Comment by LizNobriga** [comment]
Moving this issue back to 'in progress' to address the following comment:

> My friend, who is a software engineer, read through all five Q/As before calling me. None of them directly say "Most employers are required to give two weeks of sick leave for Coronavirus screening, testing, treatment or taking care of family under Families First Coronavirus Response Act (FFCRA)."  Sending to charts and table at other websites should be preceded by what people really need to know!

**Comment by abquirarte** [comment]
OK! Are we suggesting new language for this page to address the comment?

Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by LizNobriga** [comment]
We do have info on FFCRA within accordions on the page, but can better surface in next iteration to ensure people find what they need to know more quickly. I'll be drafting something and sending to @thepegisin for review!
