### ISSUE TITLE
Windows compatability

### ISSUE THREAD

**Issue by aaronhans** [cagov/covid19#801]
Thanks for discovering how to get the covid site build working on Windows Mark!

Is there any way to get that build script to work cross platform? Let's do some research on how other people have handled this and see if there is any way we can make that happen even if we have to slightly change how our scripts work by using code to to the copy operation or something.

We should immediately add the directions you discovered to get it working on Windows to the readme.md

**Comment by Mark-Tyler** [comment]
Here is what the differences:

On Windows

line 47 of package.json    "build": "npm run build:rollup && npm run build:ancient && webpack --mode production && copy .\\docs\\css\\build\\built.css .\\pages\\_includes\\built.css",

On Mac

line 47 of package.json    "build": "npm run build:rollup && npm run build:ancient && webpack --mode production && cp ./docs/css/build/built.css ./pages/_includes/built.css",

**Comment by aaronhans** [comment]
Thanks Mark! I think we can figure out how to do that copy differently so it works cross platform. The css file is created by webpack and needs to be in place for the 11ty build. We may be able to copy it at the beginning of the 11ty build script or we can use some other cross platform copy script to handle it at the right order

**Comment by aaronhans** [comment]
thanks @xjensen! https://github.com/cagov/covid19/pull/1135#pullrequestreview-458035415

**Comment by xjensen** [comment]
Quick update. While my earlier quick fixes did get the site to build on Windows, I continued to see a lot of problems in the local development watch/serve functions. So I kept working. That work can be found in the `trilogydevForWindows` branch. Here's a list of the high-level changes.

* Webpack has been removed from the build system. 
* For JS builds, everything now runs through Rollup. 
     * Babel is now integrated into the es5.js Rollup file, `rollup.config.es5.js`. This includes the preset-env module and browserlist settings. This mimics the old Webpack set-up for this file.
     * There's a combined Rollup file that can process all JS files in one pass, `rollup.config.es5.js`. Individual Rollup configs still live in their respective folders.
     * JS builds are now triggered through Gulp.
* For CSS builds, everything now runs through Gulp.
     * Instead of Webpack, there's a Gulp task to call node-sass directly. 
     * After SCSS is built, CSS purging and minifying is performed through PostCSS. Adding additional PostCSS modules here, such as autoprefixer, would be easy.
     * Because minifying is now performed during the build, we no longer need to do so within an Eleventy template filter. Those functions have been removed from the templates and `.eleventy.js` config.
     * CSS files are still built/purged separately for the homepage (`home.css`) vs. rest of the site (`built.css`).
     * A new CSS mode has been added: `development.css`. When running `npm run local:dev`, the build system will insert a full, not-purged CSS file across the whole site. For certain types of development scenarios, it may be useful to have full CSS without having to do a rebuild for every HTML change (to re-purge the CSS). This mode must be triggered via environment variable. Otherwise separate, purged files remain the default. _Let me know if interested in pursuing this further._
* The Eleventy and Webpack watchers have been replaced with a more explicit implementation of BrowserSync. This can be found in `gulpfile.js`. 
     * Controlling our own instance of BrowserSync allows us to trigger local site rebuilds at moments of our own design. Before, multiple processes were outputting multiple files to different watch locations, often triggering excessive/spurious rebuilds. This was a mess on Windows, at least. With this set-up, for example, we can wait for both the CSS files to finish before we trigger the Eleventy rebuild, etc.

That's the high-level description of the work at this moment. In general, builds perform much more quickly now. The watch functions appear to be a lot more reliable. It's working same across both Mac and PC for me. 

There's still more to do around ensuring consistency of output for both CSS and JS. In particular, I believe calling node-sass directly (instead of through sass-loader/webpack) has changed some of the defaults around how scss imports work, how files should be named, etc. I'm still seeing some weirdness in the CSS. I'll need to work through it. 

So, more to come. My day job is picking up but I'll continue to work on this as able. I'm in too deep to drop it at this point.

**Comment by xjensen** [comment]
More updates to `trilogydevForWindows`.

* The CSS weirdness seems to be worked out now. Yay!
* Development mode is way more useful now. Changes to CSS files reload in under a second.

And some to-dos.

* The new es5.js file coming out of Rollup needs some love. I'm working on IE compatibility now.

We should be ready for a PR soon.
