### ISSUE TITLE
Uploading new/updated guidance docs into site

### ISSUE THREAD

**Issue by orielgomez** [cagov/covid19#900]
There are a few PDFs that need to make their way onto the site.

Masks page guidance in:
- [ ] zh-hans
- [ ] spanish (awaiting on final document from CDSS)
[Guidance-for-Face-Coverings-zh-hans.pdf](https://github.com/cagov/covid19/files/4828882/Guidance-for-Face-Coverings-zh-hans.pdf)

Industry guidance page
- [x] switch Support working families doc in AR with edited one. 
[guidance-supportworkingfamilies-ar.pdf](https://github.com/cagov/covid19/files/4828885/guidance-supportworkingfamilies-ar.pdf)

**Comment by aaronhans** [comment]
The Arabic guidance support working families pdf has been uploaded, the page was already linking to a file at that url so no further changes necessary

The Face mask is tricky, the file is currently hosted by CDPH so our little scheme where we rewrite links in the translated pages won't work. @orielgomez is checking to see if it makes sense for us to copy that pdf and host it ourselves. If that is ok we can finish this task, if not we need to figure out a new way to localize that link

**Comment by aaronhans** [comment]
Chatted with @orielgomez about this:

We would like to add links to both the english and spanish documents on CDPH into the english post. This will show up in all translated versions of the post. Oriel confirmed this is acceptable.

This seems like the best solution because:
- We do not want to move the CDPH pdf to our servers
- We do not have any methods of rewriting offsite links in translated pages and this would be difficult to implement when we don't control the urls.

**Comment by aaronhans** [comment]
Are there any remaining tasks I can help with here @orielgomez?

**Comment by orielgomez** [comment]
@aaronhans I think we should be done here in this issue.
