### ISSUE TITLE
FIX: Hyperlinks across translated pages

### ISSUE THREAD

**Issue by abquirarte** [cagov/covid19#930]
We have a problem in our automated translations:

>When a user clicks on a link within a translated page they expect to land on a page in the same language. Instead, the link takes them to the English version. Our translated pages are not always properly being hyperlinked to their respective translated pages creating many gaps in the navigation of a user that does not Speak English. 

This may be another reason why our hits are not as high as I'd hope. 

**How might we solve for this with the vendor in the automated process?**

**Comment by aaronhans** [comment]
The best way to solve this is to migrate to a url structure where all the urls reside in a language specific directory. Since we didn't have the foresight to do this when we launched the site we have to create redirects.

- [ ] Create list of all translated urls
- [ ] Assign existing translated urls to new url pattern using 11ty metadata
- [ ] Create redirect plan from old to new urls
- [ ] Coordinate deployment

**Comment by carterm** [comment]
This might not be too hard.

- [ ] Server redirect pages with "[page]-es" to "/es/[page]" (for each language)

- [ ] Update 11ty build to match correct server output

**Comment by orielgomez** [comment]
@carterm let me know how these redirects will work. There are some things I would want to consult with you about regarding some links in the translated pages that may not fit with a simple redirect

**Comment by abquirarte** [comment]
Have we made progress on this?

**Comment by carterm** [comment]
This was completed today.
